version: "3.8"

services:

  vault-agent:
    image: hashicorp/vault:1.15
    container_name: vault-agent
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./agent/vault-agent.hcl:/vault/config.hcl
      - ./agent/template.ctmpl:/vault/template/template.ctmpl
      - ./bootstrap:/vault/bootstrap
      - ./shared:/shared          # ✅ FIX (local folder, NOT docker volume)
    environment:
      VAULT_ADDR: http://host.docker.internal:8200
    cap_add:
      - IPC_LOCK
    command: vault agent -config=/vault/config.hcl

  app:
    build: ./app
    container_name: app
    depends_on:
      - vault-agent
    volumes:
      - ./shared:/shared          # ✅ FIX

# ❌ REMOVE THIS ENTIRE SECTION
# volumes:
#   shared: