version: "3.8"

services:

  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - teamcity_logs:/opt/teamcity/logs
    environment:
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:MaxPermSize=270m
    restart: always

  teamcity-agent:
    build: ./agent
    container_name: teamcity-agent
    environment:
      SERVER_URL: http://teamcity-server:8111
    depends_on:
      - teamcity-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  teamcity_data:
  teamcity_logs:
